// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6VmPDShWaj3SCsXOr7mV7BhJ4drWvoWo',
    appId: '1:788169609434:web:552d8d88fe4272e31a95e3',
    messagingSenderId: '788169609434',
    projectId: 'notesapp-eddf3',
    authDomain: 'notesapp-eddf3.firebaseapp.com',
    databaseURL: 'https://notesapp-eddf3-default-rtdb.firebaseio.com',
    storageBucket: 'notesapp-eddf3.appspot.com',
    measurementId: 'G-QJPY64BMRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOY3hZi4ju5svm51miKX7R-dSzIQ1BdUo',
    appId: '1:788169609434:android:023eaa79c7d580541a95e3',
    messagingSenderId: '788169609434',
    projectId: 'notesapp-eddf3',
    databaseURL: 'https://notesapp-eddf3-default-rtdb.firebaseio.com',
    storageBucket: 'notesapp-eddf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA56PBmf7YV8wjbsyjq574kDms7RcGH4yM',
    appId: '1:788169609434:ios:1fec96bf359532b81a95e3',
    messagingSenderId: '788169609434',
    projectId: 'notesapp-eddf3',
    databaseURL: 'https://notesapp-eddf3-default-rtdb.firebaseio.com',
    storageBucket: 'notesapp-eddf3.appspot.com',
    androidClientId: '788169609434-fjhp5g3rb9v914b24dnn0up4rba1j7u8.apps.googleusercontent.com',
    iosClientId: '788169609434-6n5lvqegp6c94vbtgfd9m39gn22ggu97.apps.googleusercontent.com',
    iosBundleId: 'com.example.userAuthentication',
  );
}
